### ISSUE TITLE
Configurable timeout per LB rule

### ISSUE THREAD

**Issue by dj-nlx** [loxilb-io/loxilb#19]
We need to support a configurable timeout usually for TCP connections. Normally the LB should  send TCP reset in established mode, if timeout is reached.

**Comment by dj-nlx** [comment]
This functionality is already supported in AWS load-balancers and some reference can be found (here)[https://stackoverflow.com/questions/66104611/timeout-value-in-aws-alb]

**Comment by TrekkieCoder** [comment]
This feature can be enabled using the following:
```
loxicmd create lb 20.20.20.1 --tcp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1,33.33.33.1:1 --inatimeout=30
```
