### ISSUE TITLE
HTTPS Probe Support

### ISSUE THREAD

**Issue by loxi-admin** [loxilb-io/loxilb#220]
Hi,

It would be great if loxilb would be support for HTTPS probe/health-check type, because due security reason all network connections moving to encrypted approach and enpoints only answers to trusted LB (signed trusted CA).
API and CMD for CSR and private key generation would also good additions.

_Originally posted by @Slepwin in https://github.com/loxilb-io/loxilb/discussions/217_

**Comment by loxi-admin** [comment]
Requested feature has been added.

**Comment by Slepwin** [comment]
Great job! Only one question: why rootCA cert is used and not dedicated certificate (web auth client) and how it works without private key file?
