### ISSUE TITLE
Need to make sure if hashing used by loxilb is consisent 

### ISSUE THREAD

**Issue by loxi-admin** [loxilb-io/loxilb#222]
Could you please describe hash mode in details. What algorithms is used to get hash? For example 2 loxilb without HA sync (just anycast vip announce) getting the same hash for same 5-tuple and balance to the same endpoints?

_Originally posted by @Slepwin in https://github.com/loxilb-io/loxilb/discussions/221_

**Comment by dj-nlx** [comment]
Consistent hashing has been confirmed after few code fixes. Will be part of v0.8.3
