### ISSUE TITLE
clang-10 Issue Ubuntu 22.04

### ISSUE THREAD

**Issue by JLCode-tech** [loxilb-io/loxilb#246]
I am following this guide: https://loxilb-io.github.io/loxilbdocs/run/ and am currently stuck trying to make the loxilb. The previous steps for iproute2 and loxicmd worked no problem.

The current issue is the following:

`jarrodl@boba:~/loxilb$ make
cd loxilb-ebpf && make
make[1]: Entering directory '/home/jarrodl/loxilb/loxilb-ebpf'
make -C kernel
make[2]: Entering directory '/home/jarrodl/loxilb/loxilb-ebpf/kernel'
***** ERROR: Cannot find tool clang-10**
make[2]: *** [../common/common.mk:104: llvm-check] Error 1
make[2]: Leaving directory '/home/jarrodl/loxilb/loxilb-ebpf/kernel'
make[1]: *** [Makefile:17: kernel] Error 2
make[1]: Leaving directory '/home/jarrodl/loxilb/loxilb-ebpf'
make: *** [Makefile:8: subsys] Error 2`

The current clang version is the default install from ubuntu 22.04:
`jarrodl@boba:~/loxilb$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin`

- no errors with previous apt install -y command/

**Comment by socat-nlx** [comment]
I think the instructions are not updated for Ubuntu 22.04. loxilb needs clang-13  on Ubuntu 22.04. Can you try ```apt install -y clang-13``` and retry compilation ?

**Comment by JLCode-tech** [comment]
That works ! - thanks team:

jarrodl@boba:~/loxilb$ sudo apt install clang-13
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libclang-common-13-dev libclang-cpp13 libclang1-13 libllvm13 llvm-13 llvm-13-dev llvm-13-linker-tools llvm-13-runtime llvm-13-tools
Suggested packages:
  clang-13-doc llvm-13-doc
The following NEW packages will be installed:
  clang-13 libclang-common-13-dev libclang-cpp13 libclang1-13 libllvm13 llvm-13 llvm-13-dev llvm-13-linker-tools llvm-13-runtime llvm-13-tools

Now make working:
jarrodl@boba:~/loxilb$ make
cd loxilb-ebpf && make 
make[1]: Entering directory '/home/jarrodl/loxilb/loxilb-ebpf'
make -C kernel
make[2]: Entering directory '/home/jarrodl/loxilb/loxilb-ebpf/kernel'
  MKDIR    staticobjs
  CC       bpf.o
  CC       btf.o
  CC       libbpf.o


Thanks team !!
