### ISSUE TITLE
possible to use this without ebpf access?

### ISSUE THREAD

**Issue by kolinfluence** [loxilb-io/loxilb#300]
possible to use this without ebpf access?

would like to try out on aws lightsail instances which doesnt allow ebpf.

possible to provide instructions on how to set up the dsr lb?

**Comment by nik-netlox** [comment]
Hi @kolinfluence,
It is not possible to run LoxiLB without eBPF but as far as AWS lightsail instances are concerned, they can be spawned with Ubuntu20.04 and Ubuntu22.04, which supports eBPF.
To know about LoxiLB's System Requirements, please visit [this](https://loxilb-io.github.io/loxilbdocs/requirements/) page.
