### ISSUE TITLE
cicd : tcp perf test failure 

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/loxilb#331]
For Ubuntu 22.04 : 
https://github.com/loxilb-io/loxilb/actions/runs/5335038490/jobs/9667976390

<img width="850" alt="Screen Shot 2023-06-21 at 11 20 56 PM" src="https://github.com/loxilb-io/loxilb/assets/75648333/08137838-07c3-44c1-9290-207e84c509e5">

The tcp test shows no result.

**Comment by TrekkieCoder** [comment]
Commit 41ecc6109bbd6708c425bf3412f9de80b3a66fd3 fixes this.
