### ISSUE TITLE
make docker-cp command can't copy file in /opt/loxilb directory

### ISSUE THREAD

**Issue by backguynn** [loxilb-io/loxilb#39]
when I run this command, I get this error message
```
docker cp /opt/loxilb/llb_ebpf_main.o 65ac58b2e101:/opt/loxilb/llb_ebpf_main.o
lstat /opt/loxilb: no such file or directory
```
It seems that docker does not have access to the /opt/ directory.

**Comment by dj-nlx** [comment]
It looks like docker user doesn't have privilege for running docker. It  looks like non-issue. Will close !!
