### ISSUE TITLE
Use apt-get instead of apt in scripts

### ISSUE THREAD

**Issue by luisgerhorst** [loxilb-io/loxilb#434]
https://github.com/loxilb-io/loxilb/blob/00b96ad49a89c8c8da7fe4b173bd5fcb353ec1e0/.github/workflows/perf.yml#L37C14-L37C211

Just noticed you are using apt. I think it is recommended to use apt-get as it has a stable API.

**Comment by nik-netlox** [comment]
Changes incorporated.
