### ISSUE TITLE
Release 0.9?

### ISSUE THREAD

**Issue by luisgerhorst** [loxilb-io/loxilb#437]
I'm a OS researcher and I would like to use loxilb as a benchmark for BPF in a paper. I noticed 0.8 was a while a go. Do you think it would be possible to tag 0.9? This would give me a well-specified version to reference.

**Comment by UltraInstinct14** [comment]
We will bump the version soon to 0.9. Since we kept waiting for a few features, 0.9 got delayed.

**Comment by UltraInstinct14** [comment]
Release 0.9.0 is now available. If you have any issues, please raise an issue or contact us via [slack](https://www.loxilb.io/members).

**Comment by luisgerhorst** [comment]
Thanks!
