### ISSUE TITLE
cicd/tcpsctpperf: Hosts ep2,3 are started but not used

### ISSUE THREAD

**Issue by luisgerhorst** [loxilb-io/loxilb#449]
https://github.com/loxilb-io/loxilb/blob/73f7935adf583cb6b6ae35026d4498eb1c98b3b1/cicd/tcpsctpperf/config.sh#L31

I believe these are not actually used. Should they be removed or does it make sense to adapt the benchmark to actually use them?

**Comment by TrekkieCoder** [comment]
Your observation is correct. These are not needed and it would be best to remove them as these might consume resources which can in some.way adversely impact the perf test itself.

**Comment by TrekkieCoder** [comment]
Closing this as per this [commit](https://github.com/loxilb-io/loxilb/pull/457)

**Comment by luisgerhorst** [comment]
I'm sorry I think there was some confusion. The MR was not ready for merging and thus did not fix this issue, it was only a request for comments regarding the benchmarking approach. Please reopen, I will close it myself when appropriate. (I'm sorry if this was not clear, I will make it more explicit next time.)

**Comment by TrekkieCoder** [comment]
Ok got it. Notices a few breaks in loxilb's cicd. I will temporarily fix this. Please double check and commit once all your changes are ready.

**Comment by luisgerhorst** [comment]
Yes, this is expected. I will create a PR with a hotfix, you either apply that or revert the whole series.

**Comment by luisgerhorst** [comment]
With https://github.com/loxilb-io/loxilb/pull/460 this should be fixed. But to repeat: https://github.com/loxilb-io/loxilb/pull/460 was not tested. I appreciate the fast merge but I intended to look at the CI output first :D - We will see I guess.

**Comment by TrekkieCoder** [comment]
The hotfix [worked](https://github.com/loxilb-io/loxilb/actions/workflows/perf.yml). Will be looking forward for your full set of perf script changes. Looks great !!
