### ISSUE TITLE
UDP probe is not working well

### ISSUE THREAD

**Issue by inhogog2** [loxilb-io/loxilb#458]
To check UDP endpoints periodically, I turn the monitor option on when creating LB rule.

But UDP probe is not working well, "ok" and "nok" are repeated irregularly although all of the UDPs are down.

I tested on the k8s environment. I used "loxilb/cicd/k8s-calico" this cicd script.

![image](https://github.com/loxilb-io/loxilb/assets/75723069/18252357-d934-400e-8ea1-02fb7d8d9717)

**Comment by TrekkieCoder** [comment]
Please double check the [fix](https://github.com/loxilb-io/loxilb/pull/459)

**Comment by TrekkieCoder** [comment]
@inhogog2  confirmed fix to be working fine.
