### ISSUE TITLE
Can loxilb work as non-default gateway?

### ISSUE THREAD

**Issue by liyimeng** [loxilb-io/loxilb#464]
I learn loxilb from reddit.  A Quick Look on the docs, seem fuallnat is supported.  but when I see through all the demo topology, LB node is always serving as default gateway as the same time.  I am not sure if this the case, or it is just a coincident. 

Anther question is, when working in fullnat, it is possible for real server to see the client real IP address, but not the gateway IP address?

**Comment by nik-netlox** [comment]
Hello @liyimeng, Yes, LoxiLB can work as a non-default gateway. And, it is not possible to see client's real IP address when you use fullnat mode.

**Comment by liyimeng** [comment]
@nik-netlox Thanks for your answer!  Client IP might good to have since fail2ban-liked program need it. I google around, only find some hacky way to solve the problem. it is a pity.

**Comment by nik-netlox** [comment]
@liyimeng, To preserve client's IP address, you must use default mode. If you have deployed loxilb as default gateway then it is fine otherwise there are two options: 
1) Put selective routes for return traffic (if you know client's IP range) to go towards loxilb.
2) Or use loxilb with DSR mode.

**Comment by liyimeng** [comment]
Thanks @nik-netlox  I got it!
