### ISSUE TITLE
loxilb docker size review 

### ISSUE THREAD

**Issue by codeSnip12** [loxilb-io/loxilb#482]
Sometimes, it takes a little longer to docker pull loxilb image due to its slightly large size. It would be great if the size/layers can be reduced.

**Comment by TrekkieCoder** [comment]
After #595 , image size has drastically reduced (previously 1.7GB)
```
REPOSITORY                  TAG               IMAGE ID             CREATED AT                      SIZE
ghcr.io/loxilb-io/loxilb    latest            bec94dc94287   2024-03-19 13:57:22       230MB

```
