### ISSUE TITLE
Loxilb does not work on flannel.x interfaces

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/loxilb#495]
**Describe the bug**
If loxilb is run without any blacklist filter, all communication(clusterIP, node-port etc) should still work fine but it does not especially over flannel.x

**To Reproduce**
Run loxilb.yml without any --blacklist argument. And try to connect k8s service node-port via flannel interface of another node.

**Expected behavior**
Should be able to connect.

**Screenshots**
None right now

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Kernel Version: 5.15.x
 - LoxiLB Version: latest
 - Cloud Environment: on-prem
 - K8s Version: v1.28.5 (running flannel)

**Comment by TrekkieCoder** [comment]
Currently it should be supported fine. Closing this !!
