### ISSUE TITLE
Direct host route addition cause traffic forwarding to stop working

### ISSUE THREAD

**Issue by bhati-github** [loxilb-io/loxilb#534]
**Describe the bug**
When we deploy our microservices along with loxilb helm chart, we have seen that there is a direct host route added inside master node. 
192.168.10.1 dev ens3 proto dhcp scope link src 192.168.10.10 metric 100

All routes are as follows:
root@master:/# ip route
default via 192.168.10.1 dev ens3 proto dhcp src 192.168.10.10 metric 100
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink
10.244.3.0/24 via 10.244.3.0 dev flannel.1 onlink
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.10.0/24 dev ens3 proto kernel scope link src 192.168.10.10
192.168.10.1 dev ens3 proto dhcp scope link src 192.168.10.10 metric 100   [This route is causing issues]

Our VM IP addresses are as follows:
master node: 192.168.10.10
worker-1: 192.168.10.40
worker-2: 192.168.10.50
worker-3: 192.168.10.60

In host machine, IP address of virbr1 is as follows:
#ip addr show virbr1
239: virbr1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:91:5b:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.1/24 brd 192.168.10.255 scope global virbr1
       valid_lft forever preferred_lft forever

**To Reproduce**
Create a multi-node kubernetes [v1.25.10] cluster with 1 master and 3 worker nodes. IP address for the nodes should come from a virtual bridge network. 

**Expected behavior**
Prevent this addition of direct host route so that traffic forwarding works fine.

**Screenshots**
![image](https://github.com/loxilb-io/loxilb/assets/49303596/ac863715-cc95-4eec-9dd0-c68baa372a3e)
![image](https://github.com/loxilb-io/loxilb/assets/49303596/63d237e9-b164-4fc1-a962-c4eab9b81b71)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Oracle Linux8, Fedora 39, RedHat9 ]
 - Kernel Version: [e.g. 5.4.1, 5.15.5]
 - LoxiLB Version: [e.g. 0.9.0, latest. If not sure run: loxilb -v]
 - Cloud Environment: [e.g. AWS, OCI, GCP, On-prem]
 - K8s Version [e.g. 1.27, 1.29, EKS-1.27, Openshift 4.12] 

**Additional context**
Workaround is to manually delete this route and restart loxilb pod.

**Comment by UltraInstinct14** [comment]
#533 merged. Please double check !!

**Comment by bhati-github** [comment]
Sure, I will redeploy again now with latest image and update..

**Comment by bhati-github** [comment]
It is still present ... I just did a re-deployment...
![image](https://github.com/loxilb-io/loxilb/assets/49303596/bd3fb465-999b-4f7e-aa3a-2190829bee99)

**Comment by bhati-github** [comment]
I just did a reset in my multi-node k8s cluster.
![image](https://github.com/loxilb-io/loxilb/assets/49303596/2ad2d563-473c-43c1-85ba-69911ac92b5f)

Inside master node, dhcp route is present even though no deployment is made inside the cluster.

In host-machine, 192.168.10.1/24 is IP address of virbr1 interface.

![image](https://github.com/loxilb-io/loxilb/assets/49303596/621ffa67-c020-4050-874e-a8af1f145603)

**Comment by bhati-github** [comment]
I have manually deleted this dhcp route inside master node 

sudo ip route del 192.168.10.1 dev ens3

New routes are as follows:
ubuntu@master:~$ ip route
default via 192.168.10.1 dev ens3 proto dhcp src 192.168.10.10 metric 100
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink
10.244.3.0/24 via 10.244.3.0 dev flannel.1 onlink
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.10.0/24 dev ens3 proto kernel scope link src 192.168.10.10

Now, I am trying to deploy once again...Latest state is as follows:
![image](https://github.com/loxilb-io/loxilb/assets/49303596/eb42249c-2d11-4a7c-a66a-0672e8f00be8)

Output of loxicmd get route:
![image](https://github.com/loxilb-io/loxilb/assets/49303596/6ff06a77-c89a-4ba4-a1dc-4ca74ebf5039)

kubectl get nodes:
![image](https://github.com/loxilb-io/loxilb/assets/49303596/4c8f5439-5474-47f2-a675-836317764bc0)


Traffic forwarding status:
![image](https://github.com/loxilb-io/loxilb/assets/49303596/27a5ab22-6194-4fe5-bbc3-222113f0ad0b)

**Comment by bhati-github** [comment]
In above method, difference is that I manually removed that dhcp route from master node just before deployment of microservices. Traffic is working now. 
Waiting to see if Linux adds back this dhcp route once again and impacts traffic forwarding behavior of loxilb.

**Comment by UltraInstinct14** [comment]
Hi @bhati-github , In latest build, I have verified that loxilb simply ignores such route. Ofcourse it will not delete these routes by itself but will not consider them in its decision making. In the figure below, I added a route 10.10.10.253 similar to your route (manually though).  Please check the results :

<img width="557" alt="Screenshot 2024-02-20 at 9 31 04 AM" src="https://github.com/loxilb-io/loxilb/assets/75648333/b261bfa4-48f0-4738-bbd7-b65fe7adfef4">

**Comment by bhati-github** [comment]
![image](https://github.com/loxilb-io/loxilb/assets/49303596/7e18393a-85d8-441b-a0a3-e26342c3c54c)
In long run test since yesterday, traffic stats is increasing without issues.. Looks ok now.
I will just reset the cluster once again, deploy microservices without any manual deletion of that dhcp route and confirm traffic stats.

**Comment by bhati-github** [comment]
Issue is fixed now. 
Even though dhcp route is present, traffic stats is ok.
![image](https://github.com/loxilb-io/loxilb/assets/49303596/f0d0a782-2e83-4b54-9e63-23b2343c7ad8)

**Comment by bhati-github** [comment]
Closing this issue.
