### ISSUE TITLE
 Issue with BFD Patch for Fast Failover: BFD Not Stable in HA Setup with loxilb

### ISSUE THREAD

**Issue by esirame** [loxilb-io/loxilb#536]
Hi Team I tried   setting up a High Availability (HA) configuration with loxilb  "--ka=$RemoteIP" where Bidirectional Forwarding Detection (BFD) is patched for early detection and action for fast failover. However, I am experiencing instability with the BFD functionality.  

In my High Availability (HA) setup, consisting of a Master and Backup  loxilb role , the Backup node is not taking over as Master upon restarting the Master LB. Instead, it appears to be toggling between states, causing instability in the HA configuration.

**Expected Behavior:**
Upon restarting the Master  lb, the Backup node should detect the failure and seamlessly take over as Master, ensuring continuity of service without manual intervention.

Actual Behavior:
The Backup node is not taking over as Master upon restarting the Master node. Instead, it is toggling between states, leading to instability in the HA setup.

Kindly do have a look  into this issue .......Thanks in advance hoping  for some early fix on this....

**Comment by TrekkieCoder** [comment]
I tried to. reproduce this issue but could not. Test-Setup details: 

```
Oracle Cloud
Two instances of loxilb (loxilb version: 0.9.2-beta 2024_02_19-main) :
1. Running Oracle9   -  2vCPU, 8 GB RAM
2. Running Ubuntu20.04 - 2vCPU, 8 GB RAM
```
Topology is simple - 

```mermaid
graph LR;
    LoxiLB1-10.0.10.88 --> LoxiLB2-10.0.10.141;
    LoxiLB2-10.0.10.141 --> LoxiLB1-10.0.10.88;
```

* Run loxilb in Node1: 

```
sudo docker run -u root --cap-add SYS_ADMIN --net host --entrypoint=/root/loxilb-io/loxilb/loxilb --privileged -dit -v /dev/log:/dev/log --name loxilb ghcr.io/loxilb-io/loxilb:latest --ka=10.0.10.141:10.0.10.88 --cluster=10.0.10.141 --self=0
```

* Run loxilb in Node2

```
sudo docker run -u root --cap-add SYS_ADMIN --net host --entrypoint=/root/loxilb-io/loxilb/loxilb --privileged -dit -v /dev/log:/dev/log -v /home/ubuntu/loxilb-oci-config:/root/.oci --name loxilb ghcr.io/loxilb-io/loxilb:latest --ka=10.0.10.88:10.0.10.141  --cluster=10.0.10.88 --self=1
```

<b>Please note that --ka args format is remoteIP:sourceIP. If sourceIP is not provided loxilb will bind to any sourceIP it deems fit to use which may result to some issues.</b>

Check BFD state in each nodes  - 
[opc@instance-20231219-1736 ~]$ sudo docker exec -it loxilb bash -c "loxicmd get ha"
| INSTANCE | HASTATE |
|----------|---------|
| default  | BACKUP  |


ubuntu@loxilb2-20231227-2137:~$ sudo docker exec -it loxilb bash -c "loxicmd get ha"
| INSTANCE | HASTATE |
|----------|---------|
| default  | MASTER  |


In this case loxilb2 is selected as master. After doing docker stop of loxilb2, rechecked loxilb node1 status : 

[opc@instance-20231219-1736 ~]$ sudo docker exec -it loxilb bash -c "loxicmd get ha"
| INSTANCE | HASTATE |
|----------|---------|
| default  | MASTER  |

It changes as per expectation. I am also attaching logs - 

<img width="811" alt="Screenshot 2024-02-20 at 11 11 09 AM" src="https://github.com/loxilb-io/loxilb/assets/111065900/76d22fac-e01d-4af1-ad0a-56ed5c2d6053">


<img width="672" alt="Screenshot 2024-02-20 at 11 11 34 AM" src="https://github.com/loxilb-io/loxilb/assets/111065900/1dea610f-0673-464d-b52d-704ed3420529">

Also, please do not forget to comment "SetRoles" option in kube-loxilb while trying BFD.

**Comment by UltraInstinct14** [comment]
This has been tested in OCI setup. Closing this !!
