### ISSUE TITLE
BFD State Inconsistent [ Both shows MASTER ] at times 

### ISSUE THREAD

**Issue by esirame** [loxilb-io/loxilb#558]
Hi Team,
I Saw that the BFD state of the LBS  in the HA setUP to be inconsistent and it  reports to be MASTER for both at times. This is seen initially when both the LBs docker containers are started for the first time only means just after deployement.

[root@LoxilbVM-1 ~]# docker exec -it loxilb loxicmd get hastate
| INSTANCE | HASTATE |
|----------|---------|
| default  | MASTER  |
[root@LoxilbVM-1 ~]#

[root@LoxilbVM-2 ~]# docker exec -it loxilb loxicmd get hastate
| INSTANCE | HASTATE |
|----------|---------|
| default  | MASTER  |
[root@LoxilbVM-2 ~]#

However once restarted One Assumes as MASTER and the other as BACKUP . It seems there are some  some glitches and I am sure u guys will have a look on this...thnks in advance.

**Comment by UltraInstinct14** [comment]
Although unable to reproduce this issue, the condition you mentioned is possible and code has been fixed for the same, especially when timers are set to a lower than default value. It will be great if you can reconfirm after a quick test with latest docker image.

**Comment by esirame** [comment]
It seems to be working fine now ..thks your team to have a quick check on this.
