### ISSUE TITLE
sctp processing problem in 5.4 linux kernel 

### ISSUE THREAD

**Issue by TrekkieCoder** [loxilb-io/loxilb#57]
I created a sctp load-balancer rule as follows  in loxilb docker based on loxilb documentation -

```
root@5affc126b9e2:/# loxicmd  get lb -o wide
| EXTERNAL IP | PORT | PROTOCOL | SELECT | ENDPOINT IP | TARGET PORT | WEIGHT |
|-------------|------|----------|--------|-------------|-------------|--------|
| 20.20.20.1  | 2020 | sctp     |      0 | 32.32.32.1  |        5001 |      1 |
|             |      |          |        | 33.33.33.1  |        5001 |      1 |
|             |      |          |        | 34.34.34.1  |        5001 |      1 |

```

But when LB session packets are sent towards the VIP (20.20.20.1), nothing is shown in conntrack table.  However TCP rule is being processed properly. 

When kernel was upgraded to 5.13. the sctp problem went away on its own. Can somebody clarify this behavior ??

**Comment by loxi-admin** [comment]
Yes, in 5.4 kernel eBPF programs are unable to parse beyond IP header (if packet contains sctp). In recent kernels, due to improved eBPF support, this issue is not seen anymore.
