### ISSUE TITLE
Performance and scale tuning for release 0.7.0

### ISSUE THREAD

**Issue by loxi-admin** [loxilb-io/loxilb#65]
There have been many features developed and since performance is of much importance to us, we need to be make sure performance remains optimal.

**Comment by dj-nlx** [comment]
With 3-stage ebpf processing, we are able to  do the following

## Non-tunnel traffic 
```
# Before 
[  4]  0.0-10.0 sec  31.9 GBytes  27.4 Gbits/sec

# After 
[  4]  0.0-10.0 sec  34.8 GBytes  29.9 Gbits/sec
```

## Tunnel traffic
```
# Before 
[  4]  0.0-10.0 sec  27.4 GBytes  23.1 Gbits/sec

# After
[  4]  0.0-10.0 sec  29.5 GBytes  25.3 Gbits/sec
```

This includes all stateful processing and clearly provides us benefits. And the benefits outweigh the complexity involved
