### ISSUE TITLE
Ubuntu 22.04 libbpf: prog 'tc_packet_func_fast': BPF program load failed: Argument list too long 

### ISSUE THREAD

**Issue by vincentmli** [loxilb-io/loxilb#667]
**Describe the bug**
run steps below:

```
loxilb-ebpf/utils/mkllb_bpffs.sh
sudo ip link add tap0 type veth peer name tap1
sudo ifconfig tap0 up
sudo ifconfig tap1 up
sudo mkdir -p /opt/fs/bpf
sudo bpftool -d prog  load  /opt/loxilb/llb_xdp_main.o /opt/fs/bpf/xdp_packet_hook type xdp pinmaps /opt/loxilb/dp/bpf
sudo ntc filter add dev tap0 egress bpf da obj /opt/loxilb/llb_ebpf_main.o sec tc_packet_hook0
```
last ntc command result in:

```
ibbpf: prog 'tc_packet_func_fast': BPF program load failed: Argument list too long
libbpf: prog 'tc_packet_func_fast': -- BEGIN PROG LOAD LOG --


3131: (bf) r1 = r6
3132: (85) call bpf_skb_vlan_pop#19
; bpf_skb_vlan_push(ctx, bpf_ntohs(xf->l2m.dl_type), bpf_ntohs(vlan));
3133: (69) r2 = *(u16 *)(r10 -410)
; bpf_skb_vlan_push(ctx, bpf_ntohs(xf->l2m.dl_type), bpf_ntohs(vlan));
3134: (dc) r8 = be16 r8
BPF program is too large. Processed 1000001 insn. <=====exceeding 1M instruction
processed 1000001 insns (limit 1000000) max_states_per_insn 39 total_states 62642 peak_states 1411 mark_read 20
-- END PROG LOAD LOG --
libbpf: failed to load program 'tc_packet_func_fast'
libbpf: failed to load object '/opt/loxilb/llb_ebpf_main.o'
Unable to load program
```

**To Reproduce**

compile loxilb as https://loxilb-io.github.io/loxilbdocs/run/ on Ubuntu 22.04.3 VM and run

```
loxilb-ebpf/utils/mkllb_bpffs.sh
sudo ip link add tap0 type veth peer name tap1
sudo ifconfig tap0 up
sudo ifconfig tap1 up
sudo mkdir -p /opt/fs/bpf
sudo bpftool -d prog  load  /opt/loxilb/llb_xdp_main.o /opt/fs/bpf/xdp_packet_hook type xdp pinmaps /opt/loxilb/dp/bpf
sudo ntc filter add dev tap0 egress bpf da obj /opt/loxilb/llb_ebpf_main.o sec tc_packet_hook0
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS VM
 - Kernel Version: 5.15.0-86-generic
 - LoxiLB Version: 0.9.4-beta 2024_05_06-main
 - bpftool version: `bpftool v7.2.0 using libbpf v1.2 features: llvm, skeletons`

**Additional context**
Add any other context or topology about the problem here.

trying to test https://github.com/loxilb-io/loxilb/issues/666 issue on Ubuntu 22.04.03, not reproducible for that, but had this 1M instruction exceeding issue.

**Comment by TrekkieCoder** [comment]
Can you please double check this [issue](https://github.com/loxilb-io/loxilb/issues/656). Seems to be a duplicate.

**Comment by vincentmli** [comment]
yep, same problem https://github.com/loxilb-io/loxilb/issues/656#issuecomment-2088297916 and   https://github.com/loxilb-io/loxilb/files/15176449/OUTPUT_loxilb_instalation_after_curl.log shows the same `libbpf: prog 'tc_packet_func_fast': BPF program load failed: Argument list too long`

**Comment by vincentmli** [comment]
running  loxilb on host with ubuntu 22.04.02 with kernel upgraded to `6.5.0-28-generic` does not have the problem.

**Comment by UltraInstinct14** [comment]
Will take a look at this as part of #656. Hence, closing this for now.
