### ISSUE TITLE
Cross-regional Failover support with VPC peering

### ISSUE THREAD

**Issue by Rammurthy5** [loxilb-io/loxilb#696]
**Is your feature request related to a problem? Please describe.**
Currently on cloud providers, loxiLB offers HA within the same region and multi-AZs. This doesnt protect us from regional disasters. 

**Describe the solution you'd like**
It would be very helpful to get regional failover support that works seamlessly when the VPCs are peered from two different regions.

**Comment by UltraInstinct14** [comment]
The necessary support is now in. More details are documented [here](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/multi-cloud-ha.md)
