### ISSUE TITLE
Add path flag to loxicmd save to non default /etc/loxilb directory

### ISSUE THREAD

**Issue by vincentmli** [loxilb-io/loxilb#706]
**Is your feature request related to a problem? Please describe.**

BPFire UI is able to configure loxilb lb, fw, ip. but unable to save the configuration, and  if loxilb restart, the configuration configured from UI is lost.

from BPFire web UI to invoke `loxicmd save -a`,  `loxicmd save -a` failed to save to /etc/loxilb because UI does not have permission to write to /etc/loxilb directory. 

**Describe the solution you'd like**

add path flag to `loxicmd save` to save to non default /etc/loxilb directory so other non root users like UI user could execute `loxicmd save -a -p /var/ipfire/loxilb` to save the config to `/var/ipfire/loxilb` directory. it would be nice if loxilb restart could restore the config from non default /etc/loxilb directory also like /var/ipfire/loxilb

**Describe alternatives you've considered**

**Additional context**

**Comment by inhogog2** [comment]
Hi @vincentmli,

This issue has been updated.

You can specify the saving path using the -c option in the loxicmd, and to load it from that path, you will use the --config-path option when running loxilb. Please check it out.

```
loxicmd save -a -c **/root/**
IP Configuration saved in ipconfig_2024-06-28_06:43:08.txt
/usr/bin/bash -c cp -R lbconfig_2024-06-28_06:43:08.txt /root/lbconfig.txt
.....
```
```
./loxilb --config-path **/root/**
```

**Comment by vincentmli** [comment]
@inhogog2 thanks, I will test in BPFire and let you know the result

**Comment by vincentmli** [comment]
@inhogog2 I tested the feature and it works perfectly from loxicmd command line, but I still run into issue when calling loxicmd from WebUI Perl CGI program with user `nobody`  https://github.com/vincentmli/BPFire/issues/30, this  is not related to loxicmd though, something in the OS user permission level
