### ISSUE TITLE
Ingress HTTPS support

### ISSUE THREAD

**Issue by Rammurthy5** [loxilb-io/loxilb#726]
**Is your feature request related to a problem? Please describe.**
Currently Loxi supports HTTP. Adding HTTPS enhances security, e-2-e encryption.

**Describe the solution you'd like**
HTTPS support

**Comment by UltraInstinct14** [comment]
Currently, base functionality is implemented and tested minimally :

### How to create rules (standalone)
```
loxicmd create lb 10.10.10.254 --tcp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1,33.33.33.1:1 --mode=fullproxy --security=https --host=loxilb.io
loxicmd create lb 10.10.10.254 --tcp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1,33.33.33.1:1 --mode=fullproxy --security=https --host=loxilb1.io
```

### How to test: 
curl -H "Application/json" -H "Content-type: application/json" -H "HOST: loxilb.io" --insecure https://10.10.10.254:2020
curl -H "Application/json" -H "Content-type: application/json" -H "HOST: loxilb1.io" --insecure https://10.10.10.254:2020

Need to integrated and tested with loxilb-ingress next.

**Comment by UltraInstinct14** [comment]
Initial support is in. More details  [here](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/loxilb-ingress.md)

**Comment by TrekkieCoder** [comment]
The support is now available and basic features have been verified. The CICD [runs](https://github.com/loxilb-io/loxilb/actions/workflows/k3s-loxi-ingress.yml) look good. Closing this.!!
