### ISSUE TITLE
Client IP preservation and uneven load distributio

### ISSUE THREAD

**Issue by zelot1982** [loxilb-io/loxilb#745]
Can Loxilb preserve the client's source IP address and forward it to the final pod container when proxying at Layer 3 (L3), rather than using the NAT-ed node IP?

**Comment by zelot1982** [comment]
> With little bit of instrumentation it might be possible to achieve this. May I know what you mean by uneven load distribution ? Although loxilb support many [modes](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/nat.md) as well as full-proxy mode, it would be great if you could provide a simple diagram of your requirement for better understanding ?

Previously, I used MetalLB's LB solution, which allocates external IPs to LB-type services through BGP. However, when the service's externalTrafficPolicy is set to Local, if the number of pods participating in the load on each node is inconsistent, it leads to uneven load distribution. If it is set to externalTrafficPolicy: Cluster, the load is balanced across the entire cluster, but due to the NAT performed by the service, the pods cannot obtain the real IP address of the client.

**Comment by nik-netlox** [comment]
Hi @zelot1982 ,
For preserving source IP, you must create service with externalTrafficPolicy: Local with loxilb in default mode.

Regarding uneven load distribution:
Are you running loxilb in in-cluster mode? And, could you share loxicmd get lb -o wide output?
##External Mode
docker exec -it \<loxilb docker name\> loxicmd get lb -o wide

##Incluster Mode
kubectl exec -it \<loxilb pod name\> loxicmd get lb -o wide

**Comment by TrekkieCoder** [comment]
There is no more update from OP regarding this. ```externalTrafficPolicy: Local``` should solve this issue. Closing this !!
