### ISSUE TITLE
Conflicting Loxi setups in same VPC, AZ disrupt existing configuration.

### ISSUE THREAD

**Issue by Rammurthy5** [loxilb-io/loxilb#759]
**Describe the bug**
New loxi setup destroys existing Loxi setup if deployed in the same VPC and AZ despite connected to different clusters. 

**To Reproduce**
1, Set up Loxi master and backup connected to cluster A. Verify if the subnet for the given CIDR is created and ElasticIP is assigned as expected.
2, On the same VPC and AZ, Set up another Loxi master and backup connected to cluster B. use a different subnet CIDR and different ElasticIP. 
3, now you will notice the existing loxi setup is disturbed - removed the elastic ip and destroyed the subnet. 

**Expected behavior**
Despite number of existing Loxi instances in the same VPC or AZ if they have different ElasticIP, different subnet CIDR, different cluster.

**Environment (please complete the following information):**
 - OS: Talos 1.6.6
 - Kernel Version: 
 - LoxiLB Version: latest
 - Cloud Environment: AWS
 - K8s Version 1.28.3

**Comment by TrekkieCoder** [comment]
By adding argument to loxilb "--cloudinstance=test1", loxilb cluters running within same vpc can be now run.
