### ISSUE TITLE
QoS - Egress scheduler support with Linux TC

### ISSUE THREAD

**Issue by PacketCrunch** [loxilb-io/loxilb#77]
Linux already supports rich egress [QoS using TC](https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch21s02.html) . eBPF can redirect to HTB-qdisc based on queue_mapping. There needs to be a seamless way to achieve this between loxilb and TC/QoS.

**Comment by TrekkieCoder** [comment]
[tc-bpf](https://man7.org/linux/man-pages/man8/tc-bpf.8.html) man page has more info into this mapping
