### ISSUE TITLE
Cleanup cloud resources on loxilb termination

### ISSUE THREAD

**Issue by UltraInstinct14** [loxilb-io/loxilb#800]
**Describe the bug**
loxilb consumes various cloud resources when running on AWS like secondary subnets, CIDR, elasticIP etc. When all loxilb instances are terminated, the resources used by loxilb instances should be released. 

**To Reproduce**
Follow the [guide](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/eks-external.md) to create loxilb based EKS cluster.  Once everything is working, stop all the loxilb instances. Then, check the resources associated with loxilb instances in EC2 dashboard.

**Expected behavior**
No special resources associated with loxilb should remain after all instances of loxilb in a cluster are stopped/removed.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Kernel Version: 5.15.x
 - LoxiLB Version: latest 
 - Cloud Environment: AWS 
 - K8s Version: N/A

**Additional context**
N/A

**Comment by TrekkieCoder** [comment]
Supported now but only when running BFD  and not setRoles.
