### ISSUE TITLE
Least connection mode is not working

### ISSUE THREAD

**Issue by nik-netlox** [loxilb-io/loxilb#810]
**Describe the bug**
When LB rule is created with --select=lc then client receives connection refused on subsequent connections.

**To Reproduce**
loxilb create rule: loxicmd create lb 20.20.20.1 --tcp=2020:8080 --endpoints=31.31.31.1:1,32.32.32.1:1,33.33.33.1:1 --select=lc

Run server app from all endpoints and open multiple connections from client.

**Expected behavior**
Client connection request must be sent to the endpoint having least number of active connections.

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Kernel Version: 5.15
 - LoxiLB Version: latest
 - Cloud Environment: On-prem
 - K8s Version: NA

**Additional context**
NA

**Comment by TrekkieCoder** [comment]
Some issues were found and fixed. @nik-netlox Can you please reconfirm if issue is resolved ?

**Comment by nik-netlox** [comment]
This test has been validated. Closing it.
