### ISSUE TITLE
k3s base sanity fails

### ISSUE THREAD

**Issue by RMinusS** [loxilb-io/loxilb#819]
**Describe the bug**
I am trying to run k3s-base-sanity cicd locally in my system but it fails. When I checked even the main repository reports some failure : https://github.com/loxilb-io/loxilb/actions/workflows/k3s-base-sanity.yml

**To Reproduce**

```
 cd cicd/k3s-base-sanity/
 ./config.sh 
 ./validation.sh
```

**Expected behavior**
It should work fine.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Kernel Version: 6.5
 - LoxiLB Version: latest
 - Cloud Environment: Local 
 - K8s Version:  v1.31 

**Additional context**
Sometimes it does works fine.

**Comment by TrekkieCoder** [comment]
@RMinusS Can you double check again with latest images ?

**Comment by RMinusS** [comment]
@TrekkieCoder  Thanks a lot for quick response and fix. Works like a charm now.
