### ISSUE TITLE
Passive stateful conntrack mode support in loxilb

### ISSUE THREAD

**Issue by TrekkieCoder** [loxilb-io/loxilb#83]
loxilb provide's its own alternate [conntrack](https://arthurchiao.art/blog/conntrack-design-and-implementation/) implementation. Some users have requested conntrack only mode where loxilb does nothing else but conntrack mode. It might be an interesting feature for quick debugging in the cloud-native networking arena without affecting anything.

**Comment by loxi-admin** [comment]
This feature is down the priority list unless community has need for it. For now, closing it.
