### ISSUE TITLE
Support for sctp load-balancer end-point health-check

### ISSUE THREAD

**Issue by PacketCrunch** [loxilb-io/loxilb#84]
We had gh-24 for load-balancer end-point health checks but sctp sessions require special handling as goLang's net package does not seem to support sctp yet.

**Comment by TrekkieCoder** [comment]
For tcp/udp, we do some trivial things [here](https://github.com/loxilb-io/loxilib/blob/main/serviceprobe.go) but need to cover this case.

**Comment by ragoragino** [comment]
Happy to take this one. I have taken a look at whether we could use something along the lines of native (for UNIX) SCTP support [here](https://github.com/loxilb-io/loxilib/compare/main...ragoragino:loxilib:rkisel/sctp). Let me know if it would make sense to open a PR with these changes (after some cleaning and also adding some tests), or whether other approaches would be preferred.

**Comment by dj-nlx** [comment]
I think this approach is fine. Please go ahead !!

**Comment by loxi-admin** [comment]
With upcoming release, we will monitor sctp end-point with ping. Although will wait for @ragoragino 's  final patch.
