### ISSUE TITLE
loadBalancerClass Kubernetes Support

### ISSUE THREAD

**Issue by dj-nlx** [loxilb-io/loxilb#98]
### Discussed in https://github.com/loxilb-io/loxilb/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **infinitydon** September 15, 2022</sup>
Hi, I will like to ask if loxilb supports the **_loadBalancerClass_** feature? 

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

This is useful in cases where it will be deployed in public cloud platforms that already have a default LoadBalancer controller that responds to LB service-type creation.</div>

**Comment by loxi-admin** [comment]
Load-balancer class is now supported via [kube-loxilb](https://github.com/loxilb-io/loxilbdocs/blob/main/docs/kube-loxilb.md)
